### ISSUE TITLE
Stormpath does support API Chaining

### ISSUE THREAD

**Issue by orubel** [mikestowe/REST-API-Multiple-Request-Chaining#2]
> > > Note this is just an example, Stormpath does not support API Chaining.

I actually have an implementation with Stormpath. Works fine.

**Comment by mikestowe** [comment]
That's awesome. However, the example provided regarding this technique of API Chaining is not supported by Stormpath. As such, there is no need to change this example.

**Comment by beapiio** [comment]
In being polite, its not APIchaining if its an impartial implementation; its 'method chaining' because you are hardcoding the links and there is no abstraction of communication to avoid the request from going outside the application and coming back in thus creating higher I/O overhead.

So yes, still has nothing to do with my implementation or my trademark.

And since I hold say over the implementation through the trademark, you need to remove the name.

**Comment by beapiio** [comment]
feel free to show me wherein the license in the product that was released with API chaining you see anything that stipulates a condition stating that if 'you say it meets conditions' you get to use the trademark???

That is not part of the license agreement that comes with the trademark. If you are misrepresenting trademark and research as you chose to do after I told you not to do at the conference, after I applied to Mulesoft and offered them my intellectualproperty and trademarks and they said 'no'... then this is a clear case of intellectual property theft.

**Comment by orubel** [comment]
I'm contacting your board members now too to let them know about this. I told you I was being patient and nice. Now we are going to cut to the heart of the matter.
